# Generated by Django 5.2.1 on 2025-10-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(choices=[("comment", "Comentario")], max_length=20),
        ),
    ]
