# Generated by Django 5.2.1 on 2025-08-07 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.IntegerField(help_text='Valoración de la composición fotográfica (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Composición')),
                ('clarity_focus', models.IntegerField(help_text='Valoración de la claridad y enfoque (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Claridad y enfoque')),
                ('lighting', models.IntegerField(help_text='Valoración de la iluminación (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Iluminación')),
                ('creativity', models.IntegerField(help_text='Valoración de la creatividad (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Creatividad')),
                ('technical_adaptation', models.IntegerField(help_text='Valoración de la adaptación técnica (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Adaptación técnica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de valoración')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.post', verbose_name='Publicación')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que valora')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'rater')},
            },
        ),
    ]
