# Generated by Django 5.2.1 on 2025-10-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_create_default_categories'),
        ('posts', '0003_postcomment_delete_comentario'),
    ]

    operations = [
    ]
