# Generated by Django 5.2.1 on 2025-09-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Opcional. Se guarda la URL de la imagen.', null=True, upload_to='profiles/', verbose_name='Foto de perfil'),
        ),
    ]
