# Generated by Django 5.2.1 on 2025-08-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='province',
        ),
    ]
