# Generated by Django 5.2.1 on 2025-10-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_appuser_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='country',
            field=models.CharField(blank=True, default=None, help_text='Opcional. País de residencia.', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='province',
            field=models.CharField(blank=True, default=None, help_text='Opcional. Provincia/Estado de residencia.', max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
