# Generated by Django 5.2.1 on 2025-10-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appuser_country_alter_appuser_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, default=None, help_text='Opcional. Biografía del usuario.', null=True, verbose_name='Biografía'),
        ),
    ]
