# Generated by Django 5.2.1 on 2025-10-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, default=None, help_text='Opcional. Biografía del usuario.', max_length=160, null=True, verbose_name='Biografía'),
        ),
    ]
